FROM python:3.12

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu && \
    pip install -r requirements.txt

WORKDIR /app/src
COPY src .

CMD [ "python", "main.py" ]
